### ISSUE TITLE
ch.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by wavemomo** [smartxworks/virtink#55]
I used CDI to do it. But there are some problems.
1. the Dockerfile is:
```
FROM ubuntu:jammy AS rootfs
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends systemd-sysv udev lsb-release cloud-init sudo openssh-server && \
    rm -rf /var/lib/apt/lists/*
```

2. the vm.yaml:
```
apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachine
metadata:
  name: test-vm
spec:
  instance:
    memory:
      size: 4Gi
    kernel:
      image: smartxworks/virtink-kernel-5.15.12
      cmdline: "console=ttyS0 root=/dev/vda rw"
    disks:
      - name: ubuntu
      - name: cloud-init
    interfaces:
      - name: pod
  volumes:
    - name: ubuntu
      persistentVolumeClaim:
        claimName: rootfs-dv
      #dataVolume:
      # volumeName: ubuntu
    - name: cloud-init
      cloudInit:
        userData: |-
          #cloud-config
          password: password
          chpasswd: { expire: False }
          ssh_pwauth: True
  networks:
    - name: pod
      pod: {}
```
when I apply the vm.yaml,the pod is runinng, but it would quit or block later.
I try to solve the problem.
1. use `kubectl logs -f vm-test-vm-xxx`:
    it looks like successfuly, but the pod will quit later.
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/86948535/191447947-1f88e9b4-47df-4695-9aae-79ec6cb26e09.png">

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/86948535/191446029-d3f5a766-3919-427b-89f9-cc493811aee9.png">

4. use `kubectl describe vm test-vm` :
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/86948535/191445624-76bb7737-e70b-42a3-abf5-444df0be5c5c.png">
